# Generated by Django 4.1.7 on 2023-03-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_join',
            new_name='data_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_shop_owner',
        ),
    ]
