# Generated by Django 4.1.7 on 2023-04-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_article_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_bt', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('BASKET', 'basket'), ('ORDER', 'order')], default='BASKET', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.article')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
            ],
        ),
    ]
