# Generated by Django 4.1.7 on 2023-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='Article',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='line',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
